### ISSUE TITLE
github actions: Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by kiron-mx** [siemens/cmp-ra-component#101]
When running the github workflow [code_quality.yml](https://github.com/siemens/cmp-ra-component/blob/main/.github/workflows/code-quality.yml), the following warning occurs:

Node.js 16 actions are deprecated. 

Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-java@v3, actions/cache@v3.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Solution might be: upgrade actions to `*@v4`

**Comment by ralienpp** [comment]
Fixed in https://github.com/siemens/cmp-ra-component/pull/113
