### ISSUE TITLE
MAC algorithm in PasswordContext config of central key generation is ignored

### ISSUE THREAD

**Issue by DDvO** [siemens/cmp-ra-component#4]
Regardless what is specified in the config file (even an invalid algorithm), some reasonable  value is used - I guess, 1.2.840.113549.2.9 (hmacWithSHA256).
This may be an issue already at LightweightCmpRa level.

**Comment by Akretsch** [comment]
For PasswordBasedEncryption please use PRF, not MAC

**Comment by DDvO** [comment]
Done
