### ISSUE TITLE
Misleading error message when config of central key gen does not support the needed key transfer method

### ISSUE THREAD

**Issue by DDvO** [siemens/cmp-ra-component#5]
When the client request leads to, e.g., password-based key encryption but this is not enabled in the config, the error given is, e.g., <br> `downstream: could not validate enrolled certificate: null`.

**Comment by DDvO** [comment]
I meanwhile suppose that this i just an instance of #3?

**Comment by Akretsch** [comment]
Please re-test with https://github.com/siemens/LightweightCmpRa/commit/3ee544ae788a971a8af23b5474c7772484829669 or later

**Comment by Akretsch** [comment]
fixed in 8f886d86ba9f82ad6a0764dc5b3df9ae79310644
