### ISSUE TITLE
Improve choice of key management technique for central key generation

### ISSUE THREAD

**Issue by DDvO** [siemens/cmp-ra-component#7]
If the EE uses signature-based protection for its request and the protection certificate does not have a keyUsage extension,
the RA must not fail but:

* should use key agreement if possible (e.g., for EC keys)
* should use key transport otherwise (e.g., for RSA keys)

**Comment by Akretsch** [comment]
fixed in 3a95248224fa9231cb3c7d67b2c270e82fb7586f

**Comment by HBrock** [comment]
keyAgreeemnt should be used in favor of keyTransport, if possible.
Is there a reason not to use keyAgreement also with RSA?

**Comment by DDvO** [comment]
RSA does not support key agreement.

**Comment by HBrock** [comment]
You are probably right. I was thinking of something like RSA-KEM (RFC5990) but that used keyTrans or a D-H variant authenticated with RSA certificates but I could not find that.
